import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { Header } from "./_components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sessioin = await auth();

  return (
    <SessionProvider session={sessioin}>
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full p-6 bg-gray-50">
          <Header />
          {children}
        </div>
      </body>
    </html>
    </SessionProvider>
  );
}
